### ISSUE TITLE
SOAP Requests with status 100 (Continue) are not handled correctly

### ISSUE THREAD

**Issue by veewee** [php-vcr/php-vcr#134]
We are implementing some magento functionality through it's SOAP API. While testing the integration, we receive following error:

```
SoapFault: looks like we got no XML document
```

After examining the request / responses, it is clear that the failing tests are receiving the HTTP status code 100 Continue. The response headers are not placed in the 'headers' part of the yml file, but are included in the body of the response.

When running the API without VCR, everything works fine.
Her is an example of a wrong entry in the yml file:

```yml
-
    request:
        method: POST
        url: 'http://test.local/modules/magento/index.php/api/v2_soap/index/'
        headers:
            Host: test.local
            Content-Type: 'text/xml; charset=utf-8; action="urn:Mage_Api_Model_Server_V2_HandlerAction"'
        body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ns1=\"urn:Magento\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:SOAP-ENC=\"http://schemas.xmlsoap.org/soap/encoding/\" SOAP-ENV:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><SOAP-ENV:Body><ns1:catalogCategoryCreate><sessionId xsi:type=\"xsd:string\">90f20522b9156328c059bff4004cddc1</sessionId><parentId xsi:type=\"xsd:int\">1</parentId><categoryData xsi:type=\"ns1:catalogCategoryEntityCreate\"><name xsi:type=\"xsd:string\">testcategory</name><is_active xsi:type=\"xsd:int\">0</is_active><available_sort_by SOAP-ENC:arrayType=\"xsd:string[1]\" xsi:type=\"ns1:ArrayOfString\"><item xsi:type=\"xsd:string\">position</item></available_sort_by><default_sort_by xsi:type=\"xsd:string\">position</default_sort_by><include_in_menu xsi:type=\"xsd:int\">0</include_in_menu></categoryData><storeView xsi:nil=\"true\"/></ns1:catalogCategoryCreate></SOAP-ENV:Body></SOAP-ENV:Envelope>\n"
    response:
        status:
            http_version: '1.1'
            code: '100'
            message: Continue
        body: "HTTP/1.1 200 OK\r\nDate: Tue, 04 Aug 2015 07:25:15 GMT\r\nServer: Apache/2.4.10 (Debian)\r\nExpires: Thu, 19 Nov 1981 08:52:00 GMT\r\nCache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0\r\nPragma: no-cache\r\nSet-Cookie: testID=rqjona4nprentq5ik6tdi1col2; expires=Tue, 04-Aug-2015 08:25:15 GMT; Max-Age=3600; path=/modules/magento; domain=test.local; HttpOnly\r\nContent-Length: 544\r\nVary: Accept-Encoding\r\nConnection: close\r\nContent-Type: text/xml; charset=UTF-8\r\n\r\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ns1=\"urn:Magento\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:SOAP-ENC=\"http://schemas.xmlsoap.org/soap/encoding/\" SOAP-ENV:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">\n<SOAP-ENV:Body>\n<ns1:catalogCategoryCreateResponse>\n<attribute_id xsi:type=\"xsd:int\">4</attribute_id>\n</ns1:catalogCategoryCreateResponse>\n</SOAP-ENV:Body>\n</SOAP-ENV:Envelope>\n"
```

I also tried some solutions involving removal of any Except header, but it seems like there is no such header available. Currently there is no workaround, except disabbling VCR for the failing tests.

**Comment by adri** [comment]
Can you try dev-master? There was a fix merged recently.

**Comment by veewee** [comment]
@adri 
Great, that seems to do the trick! Should have looked better :)
When will this bugfix be tagged?

**Comment by nicodemuz** [comment]
I'm having a very similar issue. Using latest version of php-vcr (1.5.1):

```yaml

-
    request:
        method: POST
        url: 'https://www.example.com/dummy'
        headers:
            Host: www.example.com
            Content-Type: 'text/xml; charset=utf-8;'
            SOAPAction: ''
        body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<SOAP-ENV:Envelope ...>...</SOAP-ENV:Envelope>\n"
    response:
        status:
            http_version: '1.1'
            code: '100'
            message: Continue
        headers:
            X-Note: 'Gateway Ack'
        body: "HTTP/1.1 200 OK\r\nX-Backside-Transport: OK OK,OK OK\r\nConnection: Keep-Alive\r\nTransfer-Encoding: chunked\r\nContent-Type: text/xml\r\nCache-Control: no-cache\r\nDate: Fri, 11 Dec 2020 14:05:38 GMT\r\nX-Global-Transaction-ID: e0ffe2255fd37cb213bc15d2\r\nStrict-Transport-Security: max-age=157680000\r\n\r\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soapenv:Envelope ...>...</soapenv:Envelope>"
        curl_info:
            url: 'https://...'
            content_type: text/xml
            http_code: 200
            header_size: 449
            request_size: 176
            filetime: -1
            ssl_verify_result: 0
            redirect_count: 0
            total_time: 1.148834
            namelookup_time: 0.00284
            connect_time: 0.213268
            pretransfer_time: 0.646295
            size_upload: !!float 6547
            size_download: !!float 8349
            speed_download: !!float 7272
            speed_upload: !!float 5702
            download_content_length: !!float -1
            upload_content_length: !!float 6547
            starttransfer_time: 0.856235
            redirect_time: !!float 0
            redirect_url: ''
            primary_ip: 123.123.123.123
            certinfo: {  }
            primary_port: 443
            local_ip: 123.123.123.123
            local_port: 39628
            http_version: 2
            protocol: 2
            ssl_verifyresult: 0
            scheme: HTTPS
            appconnect_time_us: 646243
            connect_time_us: 213268
            namelookup_time_us: 2840
            pretransfer_time_us: 646295
            redirect_time_us: 0
            starttransfer_time_us: 856235
            total_time_us: 1148834
```
