### ISSUE TITLE
Add request and response body formatter for more readable recordings.

### ISSUE THREAD

**Issue by adri** [php-vcr/php-vcr#19]
For easier debugging and general readability it would be nice to have `post_fields` and `body` **formatted** in the yaml file. 

For example, when calling a elastic search server the recording of a http interaction looks like this at the moment:

``` yaml
-
    request:
        method: GET
        url: 'http://localhost:9200/website/_search'
        headers:
            host: 'localhost:9200'
            content-type: 'application/x-www-form-urlencoded; charset=utf-8'
        post_fields:
            '{"sort":': { '{"_geo_distance":{"geopoint":"48.782300,9.177020","order":"asc","unit":"km"}}': '' }
    response:
        status: 200
        headers:
            Content-Type: 'application/json; charset=UTF-8'
            Content-Length: '8349'
        body: '{"took":8,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":100,"max_score":1.0,"hits":[{"_index":"website","_type":"location","_id":"4","_score":1.0, "_source" : {"id":4,"name":"Edwardtown","description":"Eos omnis inventore perferendis voluptatem nisi. Consequatur ullam voluptas et tempora. Corporis excepturi sint dolores quaerat odit quia nisi accusantium.","directions":"Ut explicabo corporis eligendi ut. Sapiente ut qui quidem explicabo optio amet velit aut. Iure sed alias asperiores perspiciatis deserunt omnis inventore mollitia.","is_private_access":false,"photos":[],"tags":[{"id":37,"tag":"aliquam","created_at":"2013-08-01T21:07:20+02:00","updated_at":"2013-08-01T21:07:20+02:00"}],"geopoint":{"lat":82.420116,"lon":33.733625},"created_at":"2009-08-20T12:08:06+02:00","updated_at":"2013-08-01T21:07:20+02:00"}}, .... }'
```

I suggest formatters for JSON and XML.
