### ISSUE TITLE
Missing request headers with Soaphook? Proxy (Squid) fails.

### ISSUE THREAD

**Issue by edwinheij** [php-vcr/php-vcr#194]
Situation **without** Soaphook enabled, these are the _Request headers_:
```
POST http://...:80/.../.../... HTTP/1.1
Host: ***.***.***
Connection: Keep-Alive
User-Agent: PHP-SOAP/5.3.3
Content-Type: application/soap+xml; charset=utf-8; action="http://.../.../..."
Content-Length: 3423
```

Situation where the Soaphook is **enabled**. Request from cassette:
```
request:
    method: POST
    url: 'http://...:80/.../.../...'
    headers:
        Host: ***.***.***
        Content-Type: 'application/soap+xml; charset=utf-8; action="http://.../.../..."'
    body: "..."
```

The response is:
```
response:
    status:
        http_version: '1.0'
        code: '417'
        message: 'Expectation Failed'
    headers:
        Server: squid/3.1.23
        Mime-Version: '1.0'
        Date: 'Fri, 14 Apr 2017 13:00:34 GMT'
        Content-Type: text/html
        Content-Length: '4428'
        X-Squid-Error: 'ERR_INVALID_REQ 0'
        Vary: Accept-Language
        Content-Language: en
        X-Cache: 'MISS from <proxy_host>
        X-Cache-Lookup: 'NONE from <proxy_host>:<proxy_port>'
        Via: '1.0 <proxy_host> (squid/3.1.23)'
        Connection: close
   body: "...."
```

The response body contains there error message (title of html page):
* The requested URL could not be retrieved

Some possible problems are (from response page body):
* Missing or unknown request method.
* Missing URL.
* Missing HTTP Identifier (HTTP/1.0).
* Request is too large.
* Content-Length missing for POST or PUT requests.
* Illegal character in hostname; underscores are not allowed.
* HTTP/1.1 Expect: feature is being asked from an HTTP/1.0 software.

In my opinion I am indeed missing some request headers when the Soaphook is enabled (Content-Length)

What I also found about Squid that it's not supporting HTTP/1.1 with version 3.1.x. v3.2.x will, but I can't update the proxy because it's not mine.
