### ISSUE TITLE
Support for effective_url

### ISSUE THREAD

**Issue by hannesl** [php-vcr/php-vcr#227]
Hi! I have a request that works fine when running against the backend, but when I use a recorded cassette I get `Undefined index: effective_url`. Looking in the recored cassette, i can find no record of that property/option.

The _effective url_ concept is mentioned both in the [PHP CURL docs](http://php.net/manual/en/function.curl-getinfo.php) and in the [Guzzle docs](http://guzzle3.readthedocs.io/http-client/http-redirects.html). Is it something that can be added to VCR?

I've tested on 1.4.1 and 1.3.x. The backend in this case is ElasticSearch, and I'm using this stack of dependencies:

* basemkhirat/elasticsearch 1.3.1
* elasticsearch/elasticsearch 5.3.0
* guzzlehttp/ringphp 1.1.0

I've tried to dig through the dependencies to find some clue as to how to implement a solution, but it's a maze. Hopefully the issue will make more sense to someone else.

Here is a stack trace:

```
[2017-11-02 22:54:57] testing.ERROR: ErrorException: Undefined index: effective_url in /Project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:284
Stack trace:
#0 /Project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(284): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/Users/hannes/S...', 284, Array)
#1 /Project/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#2 /Project/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /Project/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 /Project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(294): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#5 /Project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(171): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#6 /Project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(100): Elasticsearch\Connections\Connection->performRequest('GET', '/work/work/_sea...', Array, '{"query":{"bool...', Array, Object(Elasticsearch\Transport))
#7 /Project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1578): Elasticsearch\Transport->performRequest('GET', '/work/work/_sea...', Array, Array, Array)
#8 /Project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(952): Elasticsearch\Client->performRequest(Object(Elasticsearch\Endpoints\Search))
#9 /Project/vendor/basemkhirat/elasticsearch/src/Query.php(860): Elasticsearch\Client->search(Array)
#10 /Project/vendor/basemkhirat/elasticsearch/src/Query.php(828): Basemkhirat\Elasticsearch\Query->response(NULL)
#11 /Project/vendor/basemkhirat/elasticsearch/src/Query.php(799): Basemkhirat\Elasticsearch\Query->getResult(NULL)
...
```

Here is an abbreviated copy of my cassette:

```
-
    request:
        method: GET
        url: 'http://myhost:9200/work/work/_search?from=0&size=1'
        headers:
            Host: 'myhost:9200'
            Expect: null
            host: 'myhost:9200'
            Content-type: application/json
            Accept: application/json
        body: '{"query":{"bool":{"filter":[{"term":{"_id":"117037"}}]}}}'
    response:
        status:
            http_version: '1.1'
            code: '200'
            message: OK
        headers:
            content-type: 'application/json; charset=UTF-8'
            content-length: '10837'
        body: '{"took":0,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":1,"max_score":0.0,"hits":[...
```
