### ISSUE TITLE
CurlHelper::handleOutput() must be an instance of VCR\Response, null given

### ISSUE THREAD

**Issue by beijer** [php-vcr/php-vcr#49]
I'm getting this error while trying to use vcr and I can't find the solution to the problem:

``` php
1) DataFetcherTest::test_fetch_should_return_from_api
Argument 1 passed to VCR\Util\CurlHelper::handleOutput() must be an instance of
VCR\Response, null given, called in G:\PHP\EveFetcher\workbench\beijer\eve-fetch
er\vendor\php-vcr\php-vcr\src\VCR\LibraryHooks\CurlHook.php on line 193 and defi
ned

G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\vendor\php-vcr\php-vcr\src\VCR\Ut
il\CurlHelper.php:52
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\vendor\php-vcr\php-vcr\src\VCR\Li
braryHooks\CurlHook.php:193
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\vendor\php-vcr\php-vcr\src\VCR\Li
braryHooks\CurlHook.php:245
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\vendor\php-vcr\php-vcr\src\VCR\Li
braryHooks\CurlHook.php:150
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\vendor\guzzle\guzzle\src\Guzzle\H
ttp\Curl\CurlMulti.php:225
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\vendor\guzzle\guzzle\src\Guzzle\H
ttp\Curl\CurlMulti.php:225
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\vendor\guzzle\guzzle\src\Guzzle\H
ttp\Curl\CurlMulti.php:211
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\vendor\guzzle\guzzle\src\Guzzle\H
ttp\Curl\CurlMulti.php:105
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\vendor\guzzle\guzzle\src\Guzzle\H
ttp\Curl\CurlMultiProxy.php:91
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\vendor\guzzle\guzzle\src\Guzzle\H
ttp\Client.php:282
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\vendor\guzzle\guzzle\src\Guzzle\H
ttp\Message\Request.php:198
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\src\Beijer\EveFetcher\Core\DataFe
tcher.php:45
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\src\Beijer\EveFetcher\Core\DataFe
tcher.php:28
G:\PHP\EveFetcher\workbench\beijer\eve-fetcher\tests\DataFetcherTest.php:16
```

The fixture is getting the info it should recieve: 

``` yml
-
    request:
        method: GET
        url: 'https://api.eveonline.com/server/ServerStatus.xml.aspx'
        headers:
            host: api.eveonline.com
            user-agent: 'Guzzle/3.8.1 curl/7.30.0 PHP/5.5.2'
            content-length: 0
    response:
        status: 200
        headers:
            Transfer-Encoding: chunked
            Content-Type: 'application/xml; charset=utf-8'
            Date: 'Sun, 06 Apr 2014 15:42:06 GMT'
        body: "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>2014-04-06 15:42:07</currentTime>\r\n  <result>\r\n    <serverOpen>True</serverOpen>\r\n    <onlinePlayers>40065</onlinePlayers>\r\n  </result>\r\n  <cachedUntil>2014-04-06 15:42:19</cachedUntil>\r\n</eveapi>"
-
    request:
        method: GET
        url: 'https://api.eveonline.com/server/ServerStatus.xml.aspx'
        headers:
            host: api.eveonline.com
            user-agent: 'Guzzle/3.8.1 curl/7.30.0 PHP/5.5.2'
            content-length: 0
    response:
        status: 200
        headers:
            Transfer-Encoding: chunked
            Content-Type: 'application/xml; charset=utf-8'
            Date: 'Sun, 06 Apr 2014 15:42:20 GMT'
        body: "<?xml version='1.0' encoding='UTF-8'?>\r\n<eveapi version=\"2\">\r\n  <currentTime>2014-04-06 15:42:20</currentTime>\r\n  <result>\r\n    <serverOpen>True</serverOpen>\r\n    <onlinePlayers>40171</onlinePlayers>\r\n  </result>\r\n  <cachedUntil>2014-04-06 15:45:19</cachedUntil>\r\n</eveapi>"
```
