### ISSUE TITLE
Matching URL seems to not be working with curl requests

### ISSUE THREAD

**Issue by janhartigan** [php-vcr/php-vcr#66]
I noticed that my cassettes were being recorded, but the recorder couldn't resolve cassettes (even ones that were just created). I tracked it down to [the matchUrl method in the RequestMatcher class](https://github.com/php-vcr/php-vcr/blob/master/src/VCR/RequestMatcher.php#L23-L42):

```php
public static function matchUrl(Request $first, Request $second)
{
    if (null !== $first->getPath()) {
        $path = str_replace('#', '\\#', $first->getPath());

        if (!preg_match('#'.$path.'#', rawurldecode($second->getPath()))) {
            return false;
        }
    }

    return true;
}
```

Here are the contents of the cassette:

```yaml

-
    request:
        method: GET
        url: 'https://api.balancedpayments.com/marketplaces%3Flimit%3D2%26offset%3D0'
        headers:
            Host: api.balancedpayments.com
            Content-Type: ''
            User-Agent: balanced-php/1.1.2
            Accept: 'application/vnd.balancedpayments+json; version=1.1, application/vnd.api+json'
            Content-Length: '0'
    response:
        status: 200
        headers:
            Content-Type: application/json
            Date: 'Sun, 27 Jul 2014 02:23:01 GMT'
            Server: ngx_openresty/1.2.6.3
            Content-Length: '1487'
            Connection: keep-alive
        body: "{removed for privacy}"
```

Now the problem seems to be in how it's comparing the URLs. The value of the `$path` variable is:

```
string(38) "/marketplaces%3Flimit%3D2%26offset%3D0"
```

And the result of `$second->getPath()` is:

```
string(38) "/marketplaces%3Flimit%3D2%26offset%3D0"
```

But when you run `rawurldecode` on it, it becomes:

```
string(30) "/marketplaces?limit=2&offset=0"
```

So then the preg_match is:

```php
preg_match('#/marketplaces%3Flimit%3D2%26offset%3D0#', '/marketplaces?limit=2&offset=0')
```

Which doesn't seem to want to match. When I replace it with:

```php
if ($second->getPath() != $first->getPath()) {
```

...all is then well in the universe. I suspect there's a reason why you do it this way, though, so I'm curious what you think of this.
